services:
#    anneck_game_alpha_server.example:
#        class: Anneck\Game\AlphaServerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    alphaserver.testgame:
        class: Anneck\Game\AlphaServerBundle\Services\TestGameService
        calls:
            - [ addAction, [ @? ] ]
