# This is a world configuration ...
NAME: "WORLD ONE"
UUID: GAME_WORLD_1
Continents:
  Wollland:
    { resources: [Material, Anleitungen, Zubehör, Bücher] }
  Codecountry:
    { resources: [Material, Anleitungen, Zubehör, Bücher] }
  Bastelheim:
    { resources: [Material, Anleitungen, Zubehör, Bücher] }
# This does not work yet, but should @todo
Material:
  isCompatibleWith: [Anleitung, Zubehör]
  isActive: true
